# Generated by Django 6.0.7 on 2026-07-28 14:39

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartamentos', '0010_remove_apartamento_apartamento_unico_por_numero_e_bloco_and_more'),
        ('condominios', '0002_migrar_dados_para_condominio_inicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=30, null=True, verbose_name='RG')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('situacao', models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa')], default='ativa', max_length=7)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pessoas', to='condominios.condominio')),
            ],
            options={
                'db_table': 'pessoas',
                'ordering': ['nome_completo', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VinculoPessoaApartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('proprietario', 'Proprietário'), ('morador', 'Morador'), ('inquilino', 'Inquilino'), ('responsavel_financeiro', 'Responsável financeiro')], max_length=24)),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de fim')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_pessoas', to='apartamentos.apartamento')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_apartamentos', to='pessoas.pessoa')),
            ],
            options={
                'db_table': 'vinculos_pessoas_apartamentos',
                'ordering': ['tipo', '-ativo', '-data_inicio', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='pessoa',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('nome_completo', ''), _negated=True), ('nome_completo', django.db.models.functions.text.Trim('nome_completo'))), name='pessoa_nome_valido'),
        ),
        migrations.AddConstraint(
            model_name='pessoa',
            constraint=models.CheckConstraint(condition=models.Q(('cpf__regex', '^[0-9]{11}$')), name='pessoa_cpf_normalizado'),
        ),
        migrations.AddConstraint(
            model_name='vinculopessoaapartamento',
            constraint=models.CheckConstraint(condition=models.Q(('data_fim__isnull', True), ('data_fim__gte', models.F('data_inicio')), _connector='OR'), name='vinculo_periodo_valido'),
        ),
        migrations.AddConstraint(
            model_name='vinculopessoaapartamento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ativo', True), ('data_fim__isnull', True)), ('ativo', False), _connector='OR'), name='vinculo_ativo_sem_data_fim'),
        ),
        migrations.AddConstraint(
            model_name='vinculopessoaapartamento',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('pessoa', 'apartamento', 'tipo'), name='vinculo_ativo_unico_por_pessoa_tipo'),
        ),
        migrations.AddConstraint(
            model_name='vinculopessoaapartamento',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True), ('tipo', 'responsavel_financeiro')), fields=('apartamento',), name='responsavel_financeiro_ativo_unico'),
        ),
    ]
