# Generated by Django 6.0.7 on 2026-07-23 17:33

import configuracoes.validators
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def criar_configuracao_inicial(apps, schema_editor):
    ConfiguracaoCondominio = apps.get_model(
        "configuracoes",
        "ConfiguracaoCondominio",
    )
    ConfiguracaoCondominio.objects.get_or_create(chave=1)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoCondominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('nome', models.CharField(blank=True, max_length=150, verbose_name='Nome')),
                ('cnpj', models.CharField(blank=True, max_length=18, validators=[configuracoes.validators.validar_cnpj], verbose_name='CNPJ')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('cep', models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{3}$', 'Informe o CEP no formato 00000-000.')], verbose_name='CEP')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('administradora_nome', models.CharField(blank=True, max_length=150, verbose_name='Nome da administradora')),
                ('administradora_responsavel', models.CharField(blank=True, max_length=150, verbose_name='Responsável')),
                ('administradora_telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('administradora_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('valor_m3_gas', models.DecimalField(decimal_places=2, default=Decimal('21.02'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('999999.99'))], verbose_name='Valor do m³ do gás')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='configuracoes/logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp'])], verbose_name='Logo')),
                ('observacoes_padrao', models.TextField(blank=True, verbose_name='Observações padrão')),
                ('texto_rodape', models.TextField(blank=True, verbose_name='Texto de rodapé')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do condomínio',
                'verbose_name_plural': 'Configurações do condomínio',
                'db_table': 'configuracao_condominio',
                'constraints': [models.CheckConstraint(condition=models.Q(('chave', 1)), name='configuracao_condominio_registro_unico'), models.CheckConstraint(condition=models.Q(('valor_m3_gas__gte', 0)), name='configuracao_valor_gas_nao_negativo'), models.CheckConstraint(condition=models.Q(('valor_m3_gas__lte', Decimal('999999.99'))), name='configuracao_valor_gas_no_limite')],
            },
        ),
        migrations.RunPython(
            criar_configuracao_inicial,
            migrations.RunPython.noop,
        ),
    ]
