# Generated by Django 6.0.7 on 2026-07-25 17:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def migrar_configuracoes_e_tarifa_agua(apps, schema_editor):
    Configuracao = apps.get_model(
        "configuracoes",
        "ConfiguracaoCondominio",
    )
    Faixa = apps.get_model("configuracoes", "FaixaTarifaAgua")
    Configuracao.objects.filter(nome="").update(nome="ControlCond")
    if not Faixa.objects.exists():
        Faixa.objects.bulk_create(
            [
                Faixa(
                    consumo_inicial=inicial,
                    consumo_final=final,
                    valor=valor,
                    ordem=ordem,
                    ativa=True,
                )
                for ordem, inicial, final, valor in (
                    (1, 0, 5, Decimal("101.91")),
                    (2, 6, 10, Decimal("3.15")),
                    (3, 11, 15, Decimal("17.56")),
                    (4, 16, 20, Decimal("17.65")),
                    (5, 21, 30, Decimal("17.80")),
                    (6, 31, None, Decimal("30.12")),
                )
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaocondominio',
            name='administrador',
            field=models.CharField(blank=True, max_length=150, verbose_name='Administrador'),
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='agencia',
            field=models.CharField(blank=True, max_length=30, verbose_name='Agência'),
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='banco',
            field=models.CharField(blank=True, max_length=100, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='cargo_responsavel',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cargo do responsável'),
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='celular',
            field=models.CharField(blank=True, max_length=20, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='cidade_assinatura',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade utilizada na assinatura'),
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='codigo_barras_padrao',
            field=models.CharField(blank=True, max_length=255, verbose_name='Código de barras padrão'),
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='conta',
            field=models.CharField(blank=True, max_length=30, verbose_name='Conta'),
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='cor_destaque',
            field=models.CharField(default='#E8F1F4', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Informe uma cor hexadecimal no formato #RRGGBB.')], verbose_name='Cor de destaque'),
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='cor_primaria',
            field=models.CharField(default='#1F4E5F', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Informe uma cor hexadecimal no formato #RRGGBB.')], verbose_name='Cor primária'),
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='cor_secundaria',
            field=models.CharField(default='#64748B', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Informe uma cor hexadecimal no formato #RRGGBB.')], verbose_name='Cor secundária'),
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='dia_bonificacao_padrao',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia padrão para bonificação'),
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='dias_vencimento_padrao',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Dias padrão para vencimento'),
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='configuracoes/icones/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'ico'])], verbose_name='Ícone/favicon'),
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='favorecido_documento',
            field=models.CharField(blank=True, max_length=20, verbose_name='CPF/CNPJ do favorecido'),
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='favorecido_nome',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome do favorecido'),
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='instrucoes_pagamento',
            field=models.TextField(blank=True, verbose_name='Instruções para pagamento'),
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='mensagem_cabecalho',
            field=models.TextField(blank=True, verbose_name='Mensagem no cabeçalho'),
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='mensagem_cobranca_padrao',
            field=models.TextField(blank=True, verbose_name='Mensagem padrão de cobrança'),
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='mensagem_institucional_rodape',
            field=models.TextField(blank=True, verbose_name='Mensagem institucional do rodapé'),
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='mensagem_pagamento_antecipado',
            field=models.TextField(blank=True, verbose_name='Mensagem padrão para pagamento antecipado'),
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='moeda',
            field=models.CharField(default='BRL', max_length=3, verbose_name='Moeda'),
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='mostrar_grafico_financeiro',
            field=models.BooleanField(default=True, verbose_name='Mostrar gráfico financeiro'),
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='mostrar_resumo_financeiro',
            field=models.BooleanField(default=True, verbose_name='Mostrar resumo financeiro'),
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='mostrar_ultimos_cadastros',
            field=models.BooleanField(default=True, verbose_name='Mostrar últimos cadastros'),
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='mostrar_ultimos_pagamentos',
            field=models.BooleanField(default=True, verbose_name='Mostrar últimos pagamentos'),
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='nome_sindico',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome do síndico'),
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='numero',
            field=models.CharField(blank=True, max_length=30, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='pais',
            field=models.CharField(blank=True, default='Brasil', max_length=80, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='percentual_juros_padrao',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Percentual padrão de juros'),
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='percentual_multa_padrao',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Percentual padrão de multa'),
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='pix',
            field=models.CharField(blank=True, max_length=255, verbose_name='PIX'),
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='razao_social',
            field=models.CharField(blank=True, max_length=180, verbose_name='Razão social'),
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='responsavel_emissao',
            field=models.CharField(blank=True, max_length=150, verbose_name='Responsável pela emissão'),
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='texto_juridico',
            field=models.TextField(blank=True, verbose_name='Texto jurídico'),
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='tipo_conta',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tipo de conta'),
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='valor_bonificacao_padrao',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor padrão da bonificação'),
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='configuracaocondominio',
            name='nome',
            field=models.CharField(default='ControlCond', max_length=150, verbose_name='Nome do condomínio'),
        ),
        migrations.CreateModel(
            name='FaixaTarifaAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_inicial', models.PositiveIntegerField(verbose_name='Consumo inicial')),
                ('consumo_final', models.PositiveIntegerField(blank=True, null=True, verbose_name='Consumo final')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor')),
                ('ordem', models.PositiveSmallIntegerField(unique=True)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Faixa da tarifa de água',
                'verbose_name_plural': 'Faixas da tarifa de água',
                'db_table': 'faixas_tarifa_agua',
                'ordering': ['ordem', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('valor__gte', 0)), name='faixa_agua_valor_nao_negativo'), models.CheckConstraint(condition=models.Q(('consumo_final__isnull', True), ('consumo_final__gte', models.F('consumo_inicial')), _connector='OR'), name='faixa_agua_intervalo_valido')],
            },
        ),
        migrations.RunPython(
            migrar_configuracoes_e_tarifa_agua,
            migrations.RunPython.noop,
        ),
    ]
