# Generated by Django 6.0.7 on 2026-07-25 17:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def migrar_tarifas_atuais(apps, schema_editor):
    Configuracao = apps.get_model("configuracoes", "ConfiguracaoCondominio")
    Faixa = apps.get_model("configuracoes", "FaixaTarifaAgua")
    Tabela = apps.get_model("configuracoes", "TabelaTarifariaAgua")
    TarifaGas = apps.get_model("configuracoes", "TarifaGas")

    tabela = Tabela.objects.create(
        nome="Tabela de água inicial migrada",
        data_inicio_vigencia="2000-01-01",
        ativa=True,
        observacoes="Migrada automaticamente das regras vigentes do ControlCond.",
    )
    Faixa.objects.filter(tabela__isnull=True).update(tabela=tabela)
    configuracao = Configuracao.objects.order_by("pk").first()
    TarifaGas.objects.create(
        nome="Tarifa de gás inicial migrada",
        valor_por_m3=(
            configuracao.valor_m3_gas if configuracao else Decimal("21.02")
        ),
        data_inicio_vigencia="2000-01-01",
        ativa=True,
        observacoes="Migrada automaticamente da configuração global.",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0002_configuracaocondominio_administrador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaTarifariaAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio_vigencia', models.DateField(verbose_name='Início da vigência')),
                ('data_fim_vigencia', models.DateField(blank=True, null=True, verbose_name='Fim da vigência')),
                ('ativa', models.BooleanField(default=True, verbose_name='Disponível administrativamente')),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Tabela tarifária de água',
                'verbose_name_plural': 'Tabelas tarifárias de água',
                'db_table': 'tabelas_tarifarias_agua',
                'ordering': ['-data_inicio_vigencia', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TarifaGas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio_vigencia', models.DateField(verbose_name='Início da vigência')),
                ('data_fim_vigencia', models.DateField(blank=True, null=True, verbose_name='Fim da vigência')),
                ('ativa', models.BooleanField(default=True, verbose_name='Disponível administrativamente')),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=150)),
                ('valor_por_m3', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('999999.99'))], verbose_name='Valor por m³')),
            ],
            options={
                'verbose_name': 'Tarifa de gás',
                'verbose_name_plural': 'Tarifas de gás',
                'db_table': 'tarifas_gas',
                'ordering': ['-data_inicio_vigencia', '-id'],
            },
        ),
        migrations.AddField(
            model_name='faixatarifaagua',
            name='descricao',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='faixatarifaagua',
            name='ordem',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AddField(
            model_name='faixatarifaagua',
            name='tabela',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faixas', to='configuracoes.tabelatarifariaagua'),
        ),
        migrations.RunPython(migrar_tarifas_atuais, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='faixatarifaagua',
            name='tabela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faixas', to='configuracoes.tabelatarifariaagua'),
        ),
        migrations.AddConstraint(
            model_name='faixatarifaagua',
            constraint=models.UniqueConstraint(fields=('tabela', 'ordem'), name='faixa_agua_ordem_unica_por_tabela'),
        ),
        migrations.AddConstraint(
            model_name='faixatarifaagua',
            constraint=models.UniqueConstraint(fields=('tabela', 'consumo_inicial', 'consumo_final'), name='faixa_agua_intervalo_unico_por_tabela'),
        ),
        migrations.AddConstraint(
            model_name='tarifagas',
            constraint=models.CheckConstraint(condition=models.Q(('valor_por_m3__gte', 0)), name='tarifa_gas_valor_nao_negativo'),
        ),
    ]
