# Generated by Django 6.0.7 on 2026-07-25 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominios', '0001_initial'),
        ('configuracoes', '0003_tabelatarifariaagua_tarifagas_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='configuracaocondominio',
            name='configuracao_condominio_registro_unico',
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='condominio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracao', to='condominios.condominio'),
        ),
        migrations.AddField(
            model_name='tabelatarifariaagua',
            name='condominio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tabelas_agua', to='condominios.condominio'),
        ),
        migrations.AddField(
            model_name='tarifagas',
            name='condominio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarifas_gas', to='condominios.condominio'),
        ),
        migrations.AlterField(
            model_name='configuracaocondominio',
            name='chave',
            field=models.PositiveSmallIntegerField(default=1, editable=False),
        ),
    ]
