# Generated by Django 6.0.7 on 2026-07-25 18:10

import condominios.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominios', '0002_migrar_dados_para_condominio_inicial'),
        ('configuracoes', '0004_remove_configuracaocondominio_configuracao_condominio_registro_unico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaocondominio',
            name='condominio',
            field=models.OneToOneField(default=condominios.models.obter_condominio_padrao_id, on_delete=django.db.models.deletion.CASCADE, related_name='configuracao', to='condominios.condominio'),
        ),
        migrations.AlterField(
            model_name='tabelatarifariaagua',
            name='condominio',
            field=models.ForeignKey(default=condominios.models.obter_condominio_padrao_id, on_delete=django.db.models.deletion.PROTECT, related_name='tabelas_agua', to='condominios.condominio'),
        ),
        migrations.AlterField(
            model_name='tarifagas',
            name='condominio',
            field=models.ForeignKey(default=condominios.models.obter_condominio_padrao_id, on_delete=django.db.models.deletion.PROTECT, related_name='tarifas_gas', to='condominios.condominio'),
        ),
    ]
