# Generated by Django 6.0.7 on 2026-07-27 18:24

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominios', '0002_migrar_dados_para_condominio_inicial'),
        ('configuracoes', '0005_alter_configuracaocondominio_condominio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaocondominio',
            name='dia_vencimento_padrao',
            field=models.PositiveSmallIntegerField(default=10, help_text='Dia do mês utilizado como vencimento padrão.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia padrão de vencimento'),
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='dias_antecedencia_bonificacao',
            field=models.PositiveSmallIntegerField(default=0, help_text='Quantidade de dias antes do vencimento para aplicar a bonificação.', validators=[django.core.validators.MaxValueValidator(365)], verbose_name='Dias de antecedência para bonificação'),
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='dias_tolerancia_pagamento',
            field=models.PositiveSmallIntegerField(default=0, help_text='Quantidade de dias após o vencimento sem encargos.', validators=[django.core.validators.MaxValueValidator(365)], verbose_name='Dias de tolerância'),
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='percentual_bonificacao_padrao',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Percentual padrão de bonificação'),
        ),
        migrations.AddField(
            model_name='configuracaocondominio',
            name='tipo_juros',
            field=models.CharField(choices=[('diario', 'Diário'), ('mensal', 'Mensal')], default='mensal', max_length=7, verbose_name='Tipo de juros'),
        ),
        migrations.AddConstraint(
            model_name='configuracaocondominio',
            constraint=models.CheckConstraint(condition=models.Q(('dia_vencimento_padrao__gte', 1), ('dia_vencimento_padrao__lte', 31)), name='configuracao_dia_vencimento_valido'),
        ),
        migrations.AddConstraint(
            model_name='configuracaocondominio',
            constraint=models.CheckConstraint(condition=models.Q(('dias_tolerancia_pagamento__lte', 365)), name='configuracao_tolerancia_no_limite'),
        ),
        migrations.AddConstraint(
            model_name='configuracaocondominio',
            constraint=models.CheckConstraint(condition=models.Q(('percentual_bonificacao_padrao__gte', 0), ('percentual_bonificacao_padrao__lte', 100)), name='configuracao_percentual_bonus_valido'),
        ),
        migrations.AddConstraint(
            model_name='configuracaocondominio',
            constraint=models.CheckConstraint(condition=models.Q(('dias_antecedencia_bonificacao__lte', 365)), name='configuracao_antecedencia_bonus_no_limite'),
        ),
    ]
