# Generated by Django 6.0.7 on 2026-07-28 18:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominios', '0003_alter_vinculousuariocondominio_papel'),
        ('configuracoes', '0006_configuracaocondominio_dia_vencimento_padrao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('dias_retencao_padrao', models.PositiveIntegerField(default=365, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)], verbose_name='Retenção padrão (dias)')),
                ('mensagem_manutencao', models.TextField(blank=True, verbose_name='Mensagem de manutenção')),
                ('modo_manutencao', models.BooleanField(default=False, verbose_name='Modo de manutenção')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração global',
                'verbose_name_plural': 'Configurações globais',
                'db_table': 'configuracao_global',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('institucional', 'Institucional'), ('operacional', 'Operacional'), ('global', 'Global')], max_length=20)),
                ('valores_anteriores', models.JSONField(default=dict)),
                ('valores_novos', models.JSONField(default=dict)),
                ('origem', models.CharField(default='painel', max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('condominio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_configuracao', to='condominios.condominio')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_configuracao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoria de configuração',
                'verbose_name_plural': 'Auditorias de configurações',
                'db_table': 'auditoria_configuracoes',
                'ordering': ['-criado_em', '-id'],
            },
        ),
    ]
