# Generated by Django 6.0.7 on 2026-07-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartamento',
            options={'ordering': ['bloco', 'numero']},
        ),
        migrations.AlterField(
            model_name='apartamento',
            name='bloco',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='apartamento',
            name='numero',
            field=models.CharField(max_length=20),
        ),
    ]
