# Generated by Django 6.0.7 on 2026-07-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartamentos', '0002_alter_apartamento_options_alter_apartamento_bloco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartamento',
            name='leitura_base_agua',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='apartamento',
            name='leitura_base_gas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
