# Generated by Django 6.0.7 on 2026-07-23 16:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartamentos', '0004_alter_apartamento_leituras_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamento',
            name='leitura_base_agua',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('999999.99'))]),
        ),
        migrations.AlterField(
            model_name='apartamento',
            name='leitura_base_gas',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('999999.99'))]),
        ),
        migrations.AddConstraint(
            model_name='apartamento',
            constraint=models.CheckConstraint(condition=models.Q(('leitura_base_agua__isnull', True), ('leitura_base_agua__gte', 0), _connector='OR'), name='apartamento_base_agua_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='apartamento',
            constraint=models.CheckConstraint(condition=models.Q(('leitura_base_gas__isnull', True), ('leitura_base_gas__gte', 0), _connector='OR'), name='apartamento_base_gas_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='apartamento',
            constraint=models.CheckConstraint(condition=models.Q(('leitura_base_agua__isnull', True), ('leitura_base_agua__lte', Decimal('999999.99')), _connector='OR'), name='apartamento_base_agua_no_limite'),
        ),
        migrations.AddConstraint(
            model_name='apartamento',
            constraint=models.CheckConstraint(condition=models.Q(('leitura_base_gas__isnull', True), ('leitura_base_gas__lte', Decimal('999999.99')), _connector='OR'), name='apartamento_base_gas_no_limite'),
        ),
    ]
