# Generated by Django 6.0.7 on 2026-07-23 17:18

import django.db.models.functions.comparison
import django.db.models.functions.text
from django.db import migrations, models


def normalizar_apartamentos_existentes(apps, schema_editor):
    Apartamento = apps.get_model("apartamentos", "Apartamento")
    apartamentos = list(Apartamento.objects.order_by("id"))
    chaves = {}

    for apartamento in apartamentos:
        apartamento.numero = (apartamento.numero or "").strip()
        apartamento.bloco = (
            apartamento.bloco.strip() or None
            if apartamento.bloco is not None
            else None
        )
        apartamento.observacoes = (
            apartamento.observacoes.strip() or None
            if apartamento.observacoes is not None
            else None
        )

        if not apartamento.numero:
            raise RuntimeError(
                f"O apartamento {apartamento.pk} não possui número válido."
            )

        chave = (
            apartamento.numero.lower(),
            (apartamento.bloco or "").lower(),
        )
        if chave in chaves:
            raise RuntimeError(
                "Existem apartamentos duplicados após a normalização: "
                f"{chaves[chave]} e {apartamento.pk}."
            )
        chaves[chave] = apartamento.pk

    Apartamento.objects.bulk_update(
        apartamentos,
        ["numero", "bloco", "observacoes"],
    )


class Migration(migrations.Migration):

    dependencies = [
        ('apartamentos', '0005_alter_apartamento_leitura_base_agua_and_more'),
    ]

    operations = [
        migrations.RunPython(
            normalizar_apartamentos_existentes,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='apartamento',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('numero'), django.db.models.functions.comparison.Coalesce(django.db.models.functions.text.Lower('bloco'), models.Value('')), name='apartamento_unico_por_numero_e_bloco', violation_error_message='Já existe um apartamento com este número e bloco.'),
        ),
        migrations.AddConstraint(
            model_name='apartamento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('numero', ''), _negated=True), ('numero', django.db.models.functions.text.Trim('numero'))), name='apartamento_numero_valido', violation_error_message='O número do apartamento é obrigatório e não pode conter espaços nas extremidades.'),
        ),
        migrations.AddConstraint(
            model_name='apartamento',
            constraint=models.CheckConstraint(condition=models.Q(('bloco__isnull', True), models.Q(models.Q(('bloco', ''), _negated=True), ('bloco', django.db.models.functions.text.Trim('bloco'))), _connector='OR'), name='apartamento_bloco_normalizado'),
        ),
        migrations.AddConstraint(
            model_name='apartamento',
            constraint=models.CheckConstraint(condition=models.Q(('observacoes__isnull', True), models.Q(models.Q(('observacoes', ''), _negated=True), ('observacoes', django.db.models.functions.text.Trim('observacoes'))), _connector='OR'), name='apartamento_observacoes_normalizadas'),
        ),
    ]
