# Generated by Django 6.0.7 on 2026-07-23 18:18

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartamentos', '0006_apartamento_apartamento_unico_por_numero_e_bloco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartamento',
            name='valor_aluguel',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('99999999.99'))], verbose_name='Valor padrão do aluguel'),
        ),
        migrations.AddConstraint(
            model_name='apartamento',
            constraint=models.CheckConstraint(condition=models.Q(('valor_aluguel__gte', 0)), name='apartamento_aluguel_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='apartamento',
            constraint=models.CheckConstraint(condition=models.Q(('valor_aluguel__lte', Decimal('99999999.99'))), name='apartamento_aluguel_no_limite'),
        ),
    ]
