# Generated by Django 6.0.7 on 2026-07-25 16:56

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartamentos', '0007_apartamento_valor_aluguel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartamento',
            name='dia_limite_bonificacao',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia limite padrão da bonificação'),
        ),
        migrations.AddField(
            model_name='apartamento',
            name='valor_bonificacao',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('99999999.99'))], verbose_name='Valor padrão da bonificação'),
        ),
        migrations.AddField(
            model_name='apartamento',
            name='valor_condominio',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('99999999.99'))], verbose_name='Valor padrão do condomínio'),
        ),
        migrations.AddField(
            model_name='apartamento',
            name='valor_iptu',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('99999999.99'))], verbose_name='Valor padrão do IPTU'),
        ),
        migrations.AddConstraint(
            model_name='apartamento',
            constraint=models.CheckConstraint(condition=models.Q(('valor_condominio__gte', 0)), name='apartamento_condominio_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='apartamento',
            constraint=models.CheckConstraint(condition=models.Q(('valor_iptu__gte', 0)), name='apartamento_iptu_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='apartamento',
            constraint=models.CheckConstraint(condition=models.Q(('valor_bonificacao__gte', 0)), name='apartamento_bonificacao_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='apartamento',
            constraint=models.CheckConstraint(condition=models.Q(('dia_limite_bonificacao__isnull', True), models.Q(('dia_limite_bonificacao__gte', 1), ('dia_limite_bonificacao__lte', 31)), _connector='OR'), name='apartamento_dia_bonificacao_valido'),
        ),
        migrations.AddConstraint(
            model_name='apartamento',
            constraint=models.CheckConstraint(condition=models.Q(('valor_bonificacao', 0), ('dia_limite_bonificacao__isnull', False), _connector='OR'), name='apartamento_bonificacao_com_dia'),
        ),
    ]
