# Generated by Django 6.0.7 on 2026-07-25 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartamentos', '0008_apartamento_dia_limite_bonificacao_and_more'),
        ('condominios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartamento',
            name='condominio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apartamentos', to='condominios.condominio'),
        ),
    ]
