# Generated by Django 6.0.7 on 2026-07-25 18:10

import condominios.models
import django.db.models.deletion
import django.db.models.functions.comparison
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartamentos', '0009_apartamento_condominio'),
        ('condominios', '0002_migrar_dados_para_condominio_inicial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='apartamento',
            name='apartamento_unico_por_numero_e_bloco',
        ),
        migrations.AlterField(
            model_name='apartamento',
            name='condominio',
            field=models.ForeignKey(default=condominios.models.obter_condominio_padrao_id, on_delete=django.db.models.deletion.PROTECT, related_name='apartamentos', to='condominios.condominio'),
        ),
        migrations.AddConstraint(
            model_name='apartamento',
            constraint=models.UniqueConstraint(models.F('condominio'), django.db.models.functions.text.Lower('numero'), django.db.models.functions.comparison.Coalesce(django.db.models.functions.text.Lower('bloco'), models.Value('')), name='apartamento_unico_por_condominio_numero_bloco', violation_error_message='Já existe um apartamento com este número e bloco.'),
        ),
    ]
