# Generated by Django 6.0.7 on 2026-07-28 17:03

import django.db.models.deletion
import django.db.models.functions.comparison
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartamentos', '0010_remove_apartamento_apartamento_unico_por_numero_e_bloco_and_more'),
        ('condominios', '0003_alter_vinculousuariocondominio_papel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='apartamento',
            name='apartamento_unico_por_condominio_numero_bloco',
        ),
        migrations.AddField(
            model_name='apartamento',
            name='arquivado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartamento',
            name='arquivado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartamento',
            name='arquivado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apartamentos_arquivados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apartamento',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apartamento',
            name='identificador_backup',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='apartamento',
            name='motivo_arquivamento',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='apartamento',
            name='retencao_ate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartamento',
            name='situacao_retencao',
            field=models.CharField(choices=[('retido', 'Em retenção'), ('backup_pendente', 'Backup pendente'), ('backup_confirmado', 'Backup confirmado')], default='retido', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='apartamento',
            constraint=models.UniqueConstraint(models.F('condominio'), django.db.models.functions.text.Lower('numero'), django.db.models.functions.comparison.Coalesce(django.db.models.functions.text.Lower('bloco'), models.Value('')), condition=models.Q(('arquivado', False)), name='apartamento_ativo_unico_por_condominio', violation_error_message='Já existe um apartamento com este número e bloco.'),
        ),
    ]
