# Generated by Django 6.0.7 on 2026-07-28 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominios', '0002_migrar_dados_para_condominio_inicial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=30)),
                ('papel_anterior', models.CharField(blank=True, max_length=20)),
                ('papel_posterior', models.CharField(blank=True, max_length=20)),
                ('ativo_anterior', models.BooleanField(null=True)),
                ('ativo_posterior', models.BooleanField(null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_acesso', to='condominios.condominio')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_acesso_executadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_afetado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_acesso_recebidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auditoria_acessos',
                'ordering': ['-criado_em', '-id'],
            },
        ),
    ]
