# Generated by Django 6.0.7 on 2026-07-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriaacesso',
            name='justificativa',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditoriaacesso',
            name='operacao_global',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auditoriaacesso',
            name='origem',
            field=models.CharField(default='painel', max_length=30),
        ),
        migrations.AlterField(
            model_name='auditoriaacesso',
            name='papel_anterior',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='auditoriaacesso',
            name='papel_posterior',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
