# Generated by Django 6.0.7 on 2026-07-28 19:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auditoriaacesso_justificativa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaRemocaoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executor_id_interno', models.PositiveBigIntegerField()),
                ('usuario_alvo_id', models.PositiveBigIntegerField(db_index=True)),
                ('acao', models.CharField(choices=[('desativacao_conta', 'Desativação de conta'), ('reativacao_conta', 'Reativação de conta'), ('anonimizacao', 'Anonimização'), ('exclusao_fisica', 'Exclusão física')], max_length=30)),
                ('justificativa', models.TextField()),
                ('origem', models.CharField(default='painel_global', max_length=50)),
                ('resultado', models.CharField(max_length=30)),
                ('situacao_anterior', models.JSONField(default=dict)),
                ('situacao_posterior', models.JSONField(default=dict)),
                ('modulos_com_referencias', models.JSONField(default=dict)),
                ('operacao_global', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_remocao_executadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auditoria_remocao_usuarios',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EstadoPrivacidadeUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_anonimo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('anonimizado_em', models.DateTimeField(blank=True, null=True)),
                ('anonimizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anonimizacoes_executadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado_privacidade', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'estado_privacidade_usuarios',
            },
        ),
    ]
