# Generated by Django 6.0.7 on 2026-07-10 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartamentos', '0001_initial'),
        ('leituras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('consumo_agua', models.FloatField()),
                ('consumo_gas', models.FloatField()),
                ('valor_agua', models.FloatField(blank=True, null=True)),
                ('valor_gas', models.FloatField(blank=True, null=True)),
                ('valor_total', models.FloatField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('data_geracao', models.TextField(blank=True, null=True)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartamentos.apartamento')),
                ('leitura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leituras.leitura')),
            ],
            options={
                'db_table': 'faturas',
            },
        ),
    ]
