# Generated by Django 6.0.7 on 2026-07-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faturas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fatura",
            name="valor_agua",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="fatura",
            name="valor_gas",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="fatura",
            name="valor_total",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
