# Generated by Django 6.0.7 on 2026-07-13 14:58

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartamentos', '0002_alter_apartamento_options_alter_apartamento_bloco_and_more'),
        ('faturas', '0002_alter_fatura_valores_monetarios'),
        ('leituras', '0002_alter_leitura_options_alter_leitura_apartamento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fatura',
            options={'ordering': ['-ano', '-mes']},
        ),
        migrations.AlterField(
            model_name='fatura',
            name='apartamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faturas', to='apartamentos.apartamento'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='data_geracao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fatura',
            name='leitura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faturas', to='leituras.leitura'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga'), ('cancelada', 'Cancelada')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='valor_agua',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='valor_gas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddConstraint(
            model_name='fatura',
            constraint=models.UniqueConstraint(fields=('apartamento', 'mes', 'ano'), name='fatura_unica_por_apartamento_e_mes'),
        ),
    ]
