# Generated by Django 6.0.7 on 2026-07-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturas', '0003_alter_fatura_options_alter_fatura_apartamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatura',
            name='consumo_agua',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='consumo_gas',
            field=models.PositiveIntegerField(),
        ),
    ]
