# Generated by Django 6.0.7 on 2026-07-15 17:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturas', '0004_alter_fatura_consumo_agua_alter_fatura_consumo_gas'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='data_emissao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
