# Generated by Django 6.0.7 on 2026-07-23 16:21

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.math
from decimal import Decimal
from django.db import migrations, models
from django.db.models import Q


def preencher_retrato_de_faturas_existentes(apps, schema_editor):
    Fatura = apps.get_model("faturas", "Fatura")
    Leitura = apps.get_model("leituras", "Leitura")
    alias = schema_editor.connection.alias

    for fatura in Fatura.objects.select_related("apartamento", "leitura").iterator():
        fatura.apartamento_numero_emissao = fatura.apartamento.numero
        fatura.apartamento_bloco_emissao = fatura.apartamento.bloco

        if fatura.leitura_id is not None:
            fatura.leitura_agua_atual = fatura.leitura.leitura_agua
            fatura.leitura_gas_atual = fatura.leitura.leitura_gas

        fatura.save(
            update_fields=[
                "apartamento_numero_emissao",
                "apartamento_bloco_emissao",
                "leitura_agua_atual",
                "leitura_gas_atual",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('apartamentos', '0005_alter_apartamento_leitura_base_agua_and_more'),
        ('faturas', '0005_fatura_data_emissao'),
        ('leituras', '0004_alter_leitura_ano_alter_leitura_leitura_agua_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='apartamento_bloco_emissao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fatura',
            name='apartamento_numero_emissao',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='fatura',
            name='leitura_agua_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fatura',
            name='leitura_agua_atual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fatura',
            name='leitura_gas_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fatura',
            name='leitura_gas_atual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.RunPython(
            preencher_retrato_de_faturas_existentes,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='fatura',
            name='ano',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='leitura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faturas', to='leituras.leitura'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='mes',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='valor_agua',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='valor_gas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddConstraint(
            model_name='fatura',
            constraint=models.CheckConstraint(condition=models.Q(('mes__gte', 1), ('mes__lte', 12)), name='fatura_mes_valido'),
        ),
        migrations.AddConstraint(
            model_name='fatura',
            constraint=models.CheckConstraint(condition=models.Q(('ano__gte', 2000), ('ano__lte', 9999)), name='fatura_ano_valido'),
        ),
        migrations.AddConstraint(
            model_name='fatura',
            constraint=models.CheckConstraint(condition=models.Q(('valor_agua__gte', 0)), name='fatura_valor_agua_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='fatura',
            constraint=models.CheckConstraint(condition=models.Q(('valor_gas__gte', 0)), name='fatura_valor_gas_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='fatura',
            constraint=models.CheckConstraint(condition=models.Q(('valor_total__gte', 0)), name='fatura_valor_total_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='fatura',
            constraint=models.CheckConstraint(condition=models.Q(('valor_total', django.db.models.functions.math.Round(django.db.models.expressions.CombinedExpression(models.F('valor_agua'), '+', models.F('valor_gas')), precision=2))), name='fatura_total_igual_a_soma'),
        ),
        migrations.AddConstraint(
            model_name='fatura',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pendente', 'paga', 'cancelada'])), name='fatura_status_valido'),
        ),
    ]
