# Generated by Django 6.0.7 on 2026-07-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartamentos', '0006_apartamento_apartamento_unico_por_numero_e_bloco_and_more'),
        ('faturas', '0006_fatura_apartamento_bloco_emissao_and_more'),
        ('leituras', '0004_alter_leitura_ano_alter_leitura_leitura_agua_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fatura',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('leitura_agua_anterior__isnull', True), ('leitura_agua_atual__isnull', True)), models.Q(('leitura_agua_anterior__isnull', False), ('leitura_agua_atual__gte', models.F('leitura_agua_anterior')), ('leitura_agua_atual__isnull', False)), _connector='OR'), name='fatura_leituras_agua_coerentes'),
        ),
        migrations.AddConstraint(
            model_name='fatura',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('leitura_gas_anterior__isnull', True), ('leitura_gas_atual__isnull', True)), models.Q(('leitura_gas_anterior__isnull', False), ('leitura_gas_atual__gte', models.F('leitura_gas_anterior')), ('leitura_gas_atual__isnull', False)), _connector='OR'), name='fatura_leituras_gas_coerentes'),
        ),
    ]
