# Generated by Django 6.0.7 on 2026-07-16 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturas', '0006_fatura_apartamento_bloco_emissao_and_more'),
        ('leituras', '0004_alter_leitura_ano_alter_leitura_leitura_agua_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatura',
            name='leitura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faturas', to='leituras.leitura'),
        ),
    ]
