# Generated by Django 6.0.7 on 2026-07-23 17:40

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartamentos', '0006_apartamento_apartamento_unico_por_numero_e_bloco_and_more'),
        ('faturas', '0007_fatura_fatura_leituras_agua_coerentes_and_more'),
        ('leituras', '0004_alter_leitura_ano_alter_leitura_leitura_agua_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='valor_m3_gas_emissao',
            field=models.DecimalField(decimal_places=2, default=Decimal('21.02'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('999999.99'))]),
        ),
        migrations.AddConstraint(
            model_name='fatura',
            constraint=models.CheckConstraint(condition=models.Q(('valor_m3_gas_emissao__gte', 0)), name='fatura_tarifa_gas_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='fatura',
            constraint=models.CheckConstraint(condition=models.Q(('valor_m3_gas_emissao__lte', Decimal('999999.99'))), name='fatura_tarifa_gas_no_limite'),
        ),
    ]
