# Generated by Django 6.0.7 on 2026-07-23 18:18

import django.core.validators
import django.db.models.expressions
import django.db.models.functions.math
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartamentos', '0007_apartamento_valor_aluguel_and_more'),
        ('faturas', '0008_fatura_valor_m3_gas_emissao_and_more'),
        ('leituras', '0004_alter_leitura_ano_alter_leitura_leitura_agua_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fatura',
            name='fatura_total_igual_a_soma',
        ),
        migrations.AddField(
            model_name='fatura',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('99999999.99'))]),
        ),
        migrations.AddField(
            model_name='fatura',
            name='valor_aluguel',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('99999999.99'))]),
        ),
        migrations.AddConstraint(
            model_name='fatura',
            constraint=models.CheckConstraint(condition=models.Q(('valor_aluguel__gte', 0)), name='fatura_aluguel_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='fatura',
            constraint=models.CheckConstraint(condition=models.Q(('valor_aluguel__lte', Decimal('99999999.99'))), name='fatura_aluguel_no_limite'),
        ),
        migrations.AddConstraint(
            model_name='fatura',
            constraint=models.CheckConstraint(condition=models.Q(('desconto__gte', 0)), name='fatura_desconto_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='fatura',
            constraint=models.CheckConstraint(condition=models.Q(('desconto__lte', Decimal('99999999.99'))), name='fatura_desconto_no_limite'),
        ),
        migrations.AddConstraint(
            model_name='fatura',
            constraint=models.CheckConstraint(condition=models.Q(('desconto__lte', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('valor_agua'), '+', models.F('valor_gas')), '+', models.F('valor_aluguel')))), name='fatura_desconto_no_subtotal'),
        ),
        migrations.AddConstraint(
            model_name='fatura',
            constraint=models.CheckConstraint(condition=models.Q(('valor_total', django.db.models.functions.math.Round(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('valor_agua'), '+', models.F('valor_gas')), '+', models.F('valor_aluguel')), '-', models.F('desconto')), precision=2))), name='fatura_total_igual_a_soma'),
        ),
    ]
