# Generated by Django 6.0.7 on 2026-07-24 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturas', '0009_remove_fatura_fatura_total_igual_a_soma_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='data_cancelamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fatura',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HistoricoStatusFatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga'), ('cancelada', 'Cancelada')], max_length=20)),
                ('novo_status', models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga'), ('cancelada', 'Cancelada')], max_length=20)),
                ('acao', models.CharField(choices=[('pagamento_confirmado', 'Pagamento confirmado'), ('fatura_cancelada', 'Fatura cancelada'), ('pagamento_estornado', 'Pagamento estornado'), ('fatura_reaberta', 'Fatura reaberta')], max_length=30)),
                ('motivo', models.TextField(blank=True, max_length=500)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_status', to='faturas.fatura')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alteracoes_status_faturas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'historico_status_faturas',
                'ordering': ['-criado_em', '-id'],
            },
        ),
    ]
