# Generated by Django 6.0.7 on 2026-07-25 16:56

import django.core.validators
import django.db.models.expressions
import django.db.models.functions.math
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartamentos', '0008_apartamento_dia_limite_bonificacao_and_more'),
        ('faturas', '0011_merge_20260725_1200'),
        ('leituras', '0005_limitar_ano'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fatura',
            name='fatura_desconto_no_subtotal',
        ),
        migrations.RemoveConstraint(
            model_name='fatura',
            name='fatura_total_igual_a_soma',
        ),
        migrations.AddField(
            model_name='fatura',
            name='bonificacao_aplicada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fatura',
            name='dia_limite_bonificacao',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='fatura',
            name='observacao_outros',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='fatura',
            name='valor_bonificacao',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('99999999.99'))]),
        ),
        migrations.AddField(
            model_name='fatura',
            name='valor_condominio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('99999999.99'))]),
        ),
        migrations.AddField(
            model_name='fatura',
            name='valor_iptu',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('99999999.99'))]),
        ),
        migrations.AddField(
            model_name='fatura',
            name='valor_outros',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-99999999.99')), django.core.validators.MaxValueValidator(Decimal('99999999.99'))]),
        ),
        migrations.AddField(
            model_name='fatura',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('99999999.99'))]),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='fatura',
            constraint=models.CheckConstraint(condition=models.Q(('valor_condominio__gte', 0)), name='fatura_condominio_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='fatura',
            constraint=models.CheckConstraint(condition=models.Q(('valor_iptu__gte', 0)), name='fatura_iptu_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='fatura',
            constraint=models.CheckConstraint(condition=models.Q(('valor_bonificacao__gte', 0)), name='fatura_bonificacao_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='fatura',
            constraint=models.CheckConstraint(condition=models.Q(('dia_limite_bonificacao__isnull', True), models.Q(('dia_limite_bonificacao__gte', 1), ('dia_limite_bonificacao__lte', 31)), _connector='OR'), name='fatura_dia_bonificacao_valido'),
        ),
        migrations.AddConstraint(
            model_name='fatura',
            constraint=models.CheckConstraint(condition=models.Q(('valor_bonificacao', 0), ('dia_limite_bonificacao__isnull', False), _connector='OR'), name='fatura_bonificacao_com_dia'),
        ),
        migrations.AddConstraint(
            model_name='fatura',
            constraint=models.CheckConstraint(condition=models.Q(('valor_outros', 0), models.Q(('observacao_outros', ''), _negated=True), _connector='OR'), name='fatura_outros_com_observacao'),
        ),
        migrations.AddConstraint(
            model_name='fatura',
            constraint=models.CheckConstraint(condition=models.Q(('desconto__lte', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('valor_agua'), '+', models.F('valor_gas')), '+', models.F('valor_aluguel')), '+', models.F('valor_condominio')), '+', models.F('valor_iptu')), '+', models.F('valor_outros')))), name='fatura_desconto_no_subtotal'),
        ),
        migrations.AddConstraint(
            model_name='fatura',
            constraint=models.CheckConstraint(condition=models.Q(('valor_total', django.db.models.functions.math.Round(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('valor_agua'), '+', models.F('valor_gas')), '+', models.F('valor_aluguel')), '+', models.F('valor_condominio')), '+', models.F('valor_iptu')), '+', models.F('valor_outros')), '-', models.F('desconto')), precision=2))), name='fatura_total_igual_a_soma'),
        ),
    ]
