# Generated by Django 6.0.7 on 2026-07-25 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0003_tabelatarifariaagua_tarifagas_and_more'),
        ('faturas', '0012_remove_fatura_fatura_desconto_no_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='faixa_agua_utilizada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faturas_utilizadas', to='configuracoes.faixatarifaagua'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='tabela_agua_utilizada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faturas_utilizadas', to='configuracoes.tabelatarifariaagua'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='tarifa_gas_utilizada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faturas_utilizadas', to='configuracoes.tarifagas'),
        ),
    ]
