# Generated by Django 6.0.7 on 2026-07-27 19:05

import django.core.validators
from datetime import timedelta
from decimal import Decimal
from django.db import migrations, models


def congelar_regras_financeiras_existentes(apps, schema_editor):
    Fatura = apps.get_model("faturas", "Fatura")
    Configuracao = apps.get_model(
        "configuracoes",
        "ConfiguracaoCondominio",
    )
    for configuracao in Configuracao.objects.all().iterator():
        faturas = Fatura.objects.filter(
            apartamento__condominio_id=configuracao.condominio_id
        )
        faturas.update(
            dias_antecedencia_bonificacao_emissao=(
                configuracao.dias_antecedencia_bonificacao
            ),
            dias_tolerancia_emissao=(
                configuracao.dias_tolerancia_pagamento
            ),
            percentual_bonificacao_emissao=(
                configuracao.percentual_bonificacao_padrao
            ),
            percentual_juros_emissao=(
                configuracao.percentual_juros_padrao
            ),
            percentual_multa_emissao=(
                configuracao.percentual_multa_padrao
            ),
            tipo_juros_emissao=configuracao.tipo_juros,
        )
        if configuracao.percentual_bonificacao_padrao > 0:
            for fatura in faturas.filter(
                data_limite_bonificacao__isnull=True
            ).iterator():
                fatura.data_limite_bonificacao = (
                    fatura.data_vencimento
                    - timedelta(
                        days=(
                            configuracao
                            .dias_antecedencia_bonificacao
                        )
                    )
                )
                fatura.save(update_fields=["data_limite_bonificacao"])
    Fatura.objects.filter(
        status="paga",
        forma_pagamento="",
    ).update(forma_pagamento="nao_informada")


class Migration(migrations.Migration):

    dependencies = [
        ('faturas', '0014_fatura_snapshots_financeiros'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='dias_antecedencia_bonificacao_emissao',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fatura',
            name='dias_tolerancia_emissao',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fatura',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('pix', 'PIX'), ('boleto', 'Boleto'), ('transferencia', 'Transferência bancária'), ('dinheiro', 'Dinheiro'), ('cartao', 'Cartão'), ('outro', 'Outro'), ('nao_informada', 'Não informada')], max_length=20),
        ),
        migrations.AddField(
            model_name='fatura',
            name='observacoes_pagamento',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='fatura',
            name='percentual_bonificacao_emissao',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddField(
            model_name='fatura',
            name='percentual_juros_emissao',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='fatura',
            name='percentual_multa_emissao',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='fatura',
            name='tipo_juros_emissao',
            field=models.CharField(choices=[('diario', 'Diário'), ('mensal', 'Mensal')], default='mensal', max_length=7),
        ),
        migrations.RunPython(
            congelar_regras_financeiras_existentes,
            migrations.RunPython.noop,
        ),
    ]
