"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from django.utils.csp import CSP

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

def _env_bool(nome, padrao=False):
    valor = os.environ.get(nome)
    if valor is None:
        return padrao

    valor_normalizado = valor.strip().lower()
    if valor_normalizado in {"1", "true", "yes", "on"}:
        return True
    if valor_normalizado in {"0", "false", "no", "off"}:
        return False

    raise ImproperlyConfigured(
        f"{nome} deve usar um valor booleano: "
        "true/false, yes/no, on/off ou 1/0."
    )


def _env_int(nome, padrao, *, minimo=None):
    valor = os.environ.get(nome)
    if valor is None:
        numero = padrao
    else:
        try:
            numero = int(valor.strip())
        except (TypeError, ValueError) as exc:
            raise ImproperlyConfigured(
                f"{nome} deve ser um número inteiro."
            ) from exc

    if minimo is not None and numero < minimo:
        raise ImproperlyConfigured(
            f"{nome} deve ser maior ou igual a {minimo}."
        )
    return numero


def _env_list(nome, padrao=""):
    valor = os.environ.get(nome, padrao)
    return [item.strip() for item in valor.split(",") if item.strip()]


# O modo de desenvolvimento permanece como padrão para facilitar a execução
# local. Em produção, defina DJANGO_DEBUG=False e forneça DJANGO_SECRET_KEY.
DEBUG = _env_bool("DJANGO_DEBUG", True)

SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")
if not SECRET_KEY or not SECRET_KEY.strip():
    if not DEBUG:
        raise ImproperlyConfigured(
            "Defina DJANGO_SECRET_KEY ao executar o sistema em produção."
        )
    SECRET_KEY = "controlcond-chave-exclusiva-para-desenvolvimento-local-2026"

ALLOWED_HOSTS = _env_list(
    "DJANGO_ALLOWED_HOSTS",
    "localhost,127.0.0.1,[::1]",
)
CSRF_TRUSTED_ORIGINS = _env_list("DJANGO_CSRF_TRUSTED_ORIGINS")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "apartamentos.apps.ApartamentosConfig",
    "leituras.apps.LeiturasConfig",
    "faturas.apps.FaturasConfig",
    "configuracoes.apps.ConfiguracoesConfig",
    "condominios.apps.CondominiosConfig",
    "pessoas.apps.PessoasConfig",
    "contratos.apps.ContratosConfig",
    "usuarios.apps.UsuariosConfig",
    "dashboard",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.csp.ContentSecurityPolicyMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'condominios.middleware.CondominioAtivoMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'configuracoes.context_processors.configuracao_global',
                'condominios.context_processors.contexto_condominio',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()

if DATABASE_URL:
    banco_padrao = dj_database_url.config(
        env="DATABASE_URL",
        conn_max_age=_env_int("DJANGO_DB_CONN_MAX_AGE", 60, minimo=0),
        conn_health_checks=True,
    )
    if banco_padrao.get("ENGINE") != "django.db.backends.postgresql":
        raise ImproperlyConfigured(
            "DATABASE_URL deve apontar para um banco PostgreSQL."
        )
    DATABASES = {"default": banco_padrao}
else:
    caminho_banco_configurado = os.environ.get("DJANGO_DATABASE_PATH")
    CAMINHO_BANCO = Path(
        caminho_banco_configurado
        if caminho_banco_configurado and caminho_banco_configurado.strip()
        else BASE_DIR / "controlcond.db"
    )
    if not CAMINHO_BANCO.is_absolute():
        CAMINHO_BANCO = BASE_DIR / CAMINHO_BANCO

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": CAMINHO_BANCO,
            "OPTIONS": {
                "timeout": _env_int("DJANGO_SQLITE_TIMEOUT", 20, minimo=1),
                "transaction_mode": "IMMEDIATE",
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": (
            "django.contrib.staticfiles.storage.StaticFilesStorage"
            if DEBUG
            else "whitenoise.storage.CompressedManifestStaticFilesStorage"
        ),
    },
}

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# As telas operacionais usam o login já fornecido pelo painel administrativo.
LOGIN_URL = "/conta/entrar/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/conta/entrar/"
EMAIL_BACKEND = os.environ.get(
    "DJANGO_EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend"
    if DEBUG else "django.core.mail.backends.smtp.EmailBackend",
)
DEFAULT_FROM_EMAIL = os.environ.get(
    "DJANGO_DEFAULT_FROM_EMAIL", "nao-responda@controlcond.local"
)
EMAIL_HOST = os.environ.get("DJANGO_EMAIL_HOST", "localhost")
EMAIL_PORT = _env_int("DJANGO_EMAIL_PORT", 25, minimo=1)
EMAIL_HOST_USER = os.environ.get("DJANGO_EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("DJANGO_EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = _env_bool("DJANGO_EMAIL_USE_TLS", False)

# Em produção, os cookies e todo o tráfego ficam restritos a HTTPS. Os valores
# podem ser ajustados por ambiente sem manter segredos no repositório.
SECURE_SSL_REDIRECT = _env_bool("DJANGO_SECURE_SSL_REDIRECT", not DEBUG)
SESSION_COOKIE_SECURE = _env_bool("DJANGO_SESSION_COOKIE_SECURE", not DEBUG)
CSRF_COOKIE_SECURE = _env_bool("DJANGO_CSRF_COOKIE_SECURE", not DEBUG)
SECURE_HSTS_SECONDS = _env_int(
    "DJANGO_SECURE_HSTS_SECONDS",
    0,
    minimo=0,
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool(
    "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS",
    False,
)
SECURE_HSTS_PRELOAD = _env_bool("DJANGO_SECURE_HSTS_PRELOAD", False)
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"

# Ative somente quando o proxy reverso remover qualquer cabeçalho recebido do
# cliente e definir X-Forwarded-Proto com base na conexão externa real.
if _env_bool("DJANGO_TRUST_X_FORWARDED_PROTO", False):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# O Bootstrap é carregado pelo CDN jsDelivr.
# Estilos inline continuam permitidos para compatibilidade com o admin.
SECURE_CSP = {
    "default-src": [CSP.SELF],
    "base-uri": [CSP.SELF],
    "form-action": [CSP.SELF],
    "frame-ancestors": [CSP.NONE],
    "object-src": [CSP.NONE],

    "script-src": [
        CSP.SELF,
        "https://cdn.jsdelivr.net",
    ],

    "style-src": [
        CSP.SELF,
        CSP.UNSAFE_INLINE,
        "https://cdn.jsdelivr.net",
    ],

    "img-src": [
        CSP.SELF,
        "data:",
    ],

    "font-src": [
        CSP.SELF,
        "https://cdn.jsdelivr.net",
    ],
}
