# Generated by Django 6.0.7 on 2026-07-25 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Condomínio',
                'verbose_name_plural': 'Condomínios',
                'ordering': ('nome', 'id'),
            },
        ),
        migrations.CreateModel(
            name='VinculoUsuarioCondominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('proprietario', 'Proprietário'), ('administrador', 'Administrador'), ('operador', 'Operador'), ('consulta', 'Somente consulta')], max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_usuarios', to='condominios.condominio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_condominios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('condominio__nome', 'usuario__username'),
                'constraints': [models.UniqueConstraint(fields=('usuario', 'condominio'), name='vinculo_usuario_condominio_unico')],
            },
        ),
    ]
