# Generated by Django 6.0.7 on 2026-07-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominios', '0002_migrar_dados_para_condominio_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculousuariocondominio',
            name='papel',
            field=models.CharField(choices=[('proprietario', 'Proprietário'), ('proprietario_administrativo', 'Proprietário Administrativo'), ('administrador', 'Administrador'), ('operador', 'Operador'), ('consulta', 'Consulta')], max_length=30),
        ),
    ]
