# Generated by Django 6.0.7 on 2026-07-10 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('leitura_agua', models.FloatField(blank=True, null=True)),
                ('leitura_gas', models.FloatField(blank=True, null=True)),
                ('data_registro', models.TextField(blank=True, null=True)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartamentos.apartamento')),
            ],
            options={
                'db_table': 'leituras',
            },
        ),
    ]
