# Generated by Django 6.0.7 on 2026-07-13 14:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartamentos', '0002_alter_apartamento_options_alter_apartamento_bloco_and_more'),
        ('leituras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leitura',
            options={'ordering': ['-ano', '-mes']},
        ),
        migrations.AlterField(
            model_name='leitura',
            name='apartamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leituras', to='apartamentos.apartamento'),
        ),
        migrations.AlterField(
            model_name='leitura',
            name='data_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='leitura',
            constraint=models.UniqueConstraint(fields=('apartamento', 'mes', 'ano'), name='leitura_unica_por_apartamento_e_mes'),
        ),
    ]
