# Generated by Django 6.0.7 on 2026-07-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leituras', '0002_alter_leitura_options_alter_leitura_apartamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitura',
            name='leitura_agua',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='leitura',
            name='leitura_gas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
