# Generated by Django 6.0.7 on 2026-07-16 14:40

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartamentos', '0005_alter_apartamento_leitura_base_agua_and_more'),
        ('leituras', '0003_alter_leitura_leitura_agua_alter_leitura_leitura_gas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitura',
            name='ano',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='leitura',
            name='leitura_agua',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('999999.99'))]),
        ),
        migrations.AlterField(
            model_name='leitura',
            name='leitura_gas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('999999.99'))]),
        ),
        migrations.AlterField(
            model_name='leitura',
            name='mes',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddConstraint(
            model_name='leitura',
            constraint=models.CheckConstraint(condition=models.Q(('mes__gte', 1), ('mes__lte', 12)), name='leitura_mes_valido'),
        ),
        migrations.AddConstraint(
            model_name='leitura',
            constraint=models.CheckConstraint(condition=models.Q(('ano__gte', 2000)), name='leitura_ano_valido'),
        ),
        migrations.AddConstraint(
            model_name='leitura',
            constraint=models.CheckConstraint(condition=models.Q(('leitura_agua__isnull', False), ('leitura_gas__isnull', False), _connector='OR'), name='leitura_agua_ou_gas_informado'),
        ),
        migrations.AddConstraint(
            model_name='leitura',
            constraint=models.CheckConstraint(condition=models.Q(('leitura_agua__isnull', True), ('leitura_agua__gte', 0), _connector='OR'), name='leitura_agua_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='leitura',
            constraint=models.CheckConstraint(condition=models.Q(('leitura_gas__isnull', True), ('leitura_gas__gte', 0), _connector='OR'), name='leitura_gas_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='leitura',
            constraint=models.CheckConstraint(condition=models.Q(('leitura_agua__isnull', True), ('leitura_agua__lte', Decimal('999999.99')), _connector='OR'), name='leitura_agua_no_limite'),
        ),
        migrations.AddConstraint(
            model_name='leitura',
            constraint=models.CheckConstraint(condition=models.Q(('leitura_gas__isnull', True), ('leitura_gas__lte', Decimal('999999.99')), _connector='OR'), name='leitura_gas_no_limite'),
        ),
    ]
