# Generated by Django 6.0.7 on 2026-07-16 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartamentos', '0005_alter_apartamento_leitura_base_agua_and_more'),
        ('leituras', '0004_alter_leitura_ano_alter_leitura_leitura_agua_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='leitura',
            name='leitura_ano_valido',
        ),
        migrations.AlterField(
            model_name='leitura',
            name='ano',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AddConstraint(
            model_name='leitura',
            constraint=models.CheckConstraint(condition=models.Q(('ano__gte', 2000), ('ano__lte', 9999)), name='leitura_ano_valido'),
        ),
    ]
