# Generated by Django 6.0.7 on 2026-07-28 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartamentos', '0010_remove_apartamento_apartamento_unico_por_numero_e_bloco_and_more'),
        ('condominios', '0002_migrar_dados_para_condominio_inicial'),
        ('pessoas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('data_termino', models.DateField(verbose_name='Data de término')),
                ('situacao', models.CharField(choices=[('futuro', 'Futuro'), ('ativo', 'Ativo'), ('encerrado', 'Encerrado'), ('rescindido', 'Rescindido')], default='futuro', editable=False, max_length=10)),
                ('data_rescisao', models.DateField(blank=True, null=True, verbose_name='Data da rescisão')),
                ('justificativa_rescisao', models.TextField(blank=True, null=True, verbose_name='Justificativa da rescisão')),
                ('rescindido_em', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='apartamentos.apartamento')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='condominios.condominio')),
                ('pessoa_contratante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_como_contratante', to='pessoas.pessoa')),
                ('responsavel_financeiro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_como_responsavel_financeiro', to='pessoas.pessoa')),
                ('usuario_rescisao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_rescindidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contratos',
                'ordering': ['data_termino', 'apartamento__bloco', 'apartamento__numero'],
                'constraints': [models.CheckConstraint(condition=models.Q(('data_termino__gt', models.F('data_inicio'))), name='contrato_periodo_valido'), models.CheckConstraint(condition=models.Q(models.Q(('data_rescisao__isnull', False), ('justificativa_rescisao__isnull', False), ('rescindido_em__isnull', False), ('situacao', 'rescindido'), ('usuario_rescisao__isnull', False)), models.Q(('situacao', 'rescindido'), _negated=True), _connector='OR'), name='contrato_rescisao_auditada')],
            },
        ),
    ]
