# Generated by Django 6.0.7 on 2026-07-28 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartamentos', '0010_remove_apartamento_apartamento_unico_por_numero_e_bloco_and_more'),
        ('condominios', '0002_migrar_dados_para_condominio_inicial'),
        ('contratos', '0001_initial'),
        ('pessoas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaRescisaoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao_anterior', models.CharField(choices=[('futuro', 'Futuro'), ('ativo', 'Ativo'), ('encerrado', 'Encerrado'), ('rescindido', 'Rescindido')], max_length=10)),
                ('situacao_posterior', models.CharField(choices=[('futuro', 'Futuro'), ('ativo', 'Ativo'), ('encerrado', 'Encerrado'), ('rescindido', 'Rescindido')], max_length=10)),
                ('justificativa', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_rescisoes_contratos', to='apartamentos.apartamento')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_rescisoes_contratos', to='condominios.condominio')),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='auditoria_rescisao', to='contratos.contrato')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_rescisoes_contratos', to=settings.AUTH_USER_MODEL)),
                ('responsavel_financeiro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_rescisoes_como_responsavel', to='pessoas.pessoa')),
                ('vinculo_financeiro_encerrado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_encerramento_por_rescisao', to='pessoas.vinculopessoaapartamento')),
            ],
            options={
                'db_table': 'auditorias_rescisoes_contratos',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VinculoFinanceiroContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_pelo_contrato', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dependencia_vinculo_financeiro', to='contratos.contrato')),
                ('vinculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dependencias_contratos', to='pessoas.vinculopessoaapartamento')),
            ],
            options={
                'db_table': 'vinculos_financeiros_contratos',
            },
        ),
    ]
